import { useState } from 'react'
import { decideRequest, roles, exportClubReport } from '../../services/clubStore'

function Table({ columns, rows, empty = 'Chưa có dữ liệu.' }) {
  return <div className="club-table-wrap"><table className="club-table"><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td colSpan={columns.length}>{empty}</td></tr>}</tbody></table></div>
}
function RoleSelect({ value, onChange, label }) {
  return <select aria-label={label} value={value} onChange={event => onChange(event.target.value)}>{roles.map(role => <option key={role}>{role}</option>)}</select>
}
export default function ClubManagement({ active, club, update }) {
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('all')
  const [editing, setEditing] = useState(null)
  const [form, setForm] = useState({ name: '', breed: '', age: 3, owner: '', status: 'Theo dõi' })
  const [selectedRoles, setSelectedRoles] = useState({})
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [settings, setSettings] = useState({ name: club.name, location: club.location, email: club.email })
  const [race, setRace] = useState({ horseId: club.horses[0]?.id || '', event: '', date: '', position: 1 })
  const change = key => event => setForm({ ...form, [key]: event.target.value })
  function commit(next, message) { update(next, message); setNotice(message); setError('') }
  function saveHorse(event) {
    event.preventDefault()
    if (!form.name.trim() || !form.breed.trim() || !form.owner.trim()) return setError('Vui lòng nhập đầy đủ tên, giống và chủ ngựa.')
    const horse = { ...form, name: form.name.trim(), breed: form.breed.trim(), owner: form.owner.trim(), age: Number(form.age), id: editing || crypto.randomUUID() }
    if (!Number.isInteger(horse.age) || horse.age < 1 || horse.age > 40) return setError('Tuổi ngựa phải từ 1 đến 40.')
    commit({ ...club, horses: editing ? club.horses.map(item => item.id === editing ? horse : item) : [...club.horses, horse] }, editing ? 'Đã cập nhật hồ sơ ngựa.' : 'Đã thêm ngựa.')
    setEditing(null); setForm({ name: '', breed: '', age: 3, owner: '', status: 'Theo dõi' })
  }
  function decide(type, request, approved) {
    commit(decideRequest(club, type, request.id, approved, selectedRoles[request.id]), `${approved ? 'Đã duyệt' : 'Đã từ chối'}: ${request.name}.`)
  }
  const matches = text => text.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())
  let content
  if (active === 'Ngựa trong trung tâm') content = <>
    <div className="club-toolbar"><input aria-label="Tìm ngựa" placeholder="Tìm tên hoặc chủ ngựa..." value={search} onChange={event => setSearch(event.target.value)}/><select aria-label="Lọc tình trạng ngựa" value={status} onChange={event => setStatus(event.target.value)}><option value="all">Mọi tình trạng</option><option>Đủ điều kiện</option><option>Theo dõi</option><option>Nghỉ dưỡng</option></select></div>
    <Table columns={['Tên ngựa', 'Giống', 'Tuổi', 'Chủ ngựa', 'Tình trạng', 'Thao tác']} rows={club.horses.filter(horse => matches(horse.name + ' ' + horse.owner) && (status === 'all' || horse.status === status)).map(horse => <tr key={horse.id}><td>{horse.name}</td><td>{horse.breed}</td><td>{horse.age}</td><td>{horse.owner}</td><td>{horse.status}</td><td><button onClick={() => { setEditing(horse.id); setForm(horse); setError('') }}>Sửa hồ sơ</button></td></tr>)}/>
    <h2>{editing ? 'Sửa hồ sơ ngựa' : 'Thêm ngựa vào trung tâm'}</h2><form className="club-form" onSubmit={saveHorse}>
      <label>Tên ngựa<input required value={form.name} onChange={change('name')}/></label><label>Giống<input required value={form.breed} onChange={change('breed')}/></label><label>Tuổi<input type="number" min="1" max="40" required value={form.age} onChange={change('age')}/></label><label>Chủ ngựa<input required value={form.owner} onChange={change('owner')}/></label><label>Tình trạng<select value={form.status} onChange={change('status')}><option>Theo dõi</option><option>Đủ điều kiện</option><option>Nghỉ dưỡng</option></select></label><button className="manager-primary-button">{editing ? 'Lưu thay đổi' : 'Thêm ngựa'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm({ name: '', breed: '', age: 3, owner: '', status: 'Theo dõi' }) }}>Hủy chỉnh sửa</button>}
    </form></>
  else if (active === 'Duyệt đăng ký ngựa' || active === 'Yêu cầu tham gia') {
    const horse = active === 'Duyệt đăng ký ngựa'
    const requests = horse ? club.horseRequests : club.memberRequests
    content = <><div className="club-toolbar"><select aria-label="Lọc trạng thái yêu cầu" value={status} onChange={event => setStatus(event.target.value)}><option value="all">Mọi trạng thái</option><option value="pending">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="rejected">Đã từ chối</option></select></div><Table columns={['Tên', horse ? 'Chủ ngựa' : 'Email', horse ? 'Giống' : 'Vai trò', 'Trạng thái', 'Thao tác']} rows={requests.filter(request => status === 'all' || request.status === status).map(request => <tr key={request.id}><td>{request.name}</td><td>{horse ? request.owner : request.email}</td><td>{horse ? request.breed : <RoleSelect label={`Vai trò của ${request.name}`} value={selectedRoles[request.id] || request.role} onChange={role => setSelectedRoles({ ...selectedRoles, [request.id]: role })}/>}</td><td>{({ pending: 'Chờ duyệt', approved: 'Đã duyệt', rejected: 'Đã từ chối' })[request.status]}</td><td>{request.status === 'pending' ? <div className="club-actions"><button onClick={() => decide(horse ? 'horse' : 'member', request, true)}>Duyệt</button><button onClick={() => decide(horse ? 'horse' : 'member', request, false)}>Từ chối</button></div> : 'Đã xử lý'}</td></tr>)}/></>
  } else if (active === 'Nhân sự') content = <><div className="club-toolbar"><input aria-label="Tìm nhân sự" placeholder="Tìm tên hoặc email..." value={search} onChange={event => setSearch(event.target.value)}/></div><Table columns={['Họ tên', 'Email', 'Vai trò', 'Trạng thái', 'Thao tác']} rows={club.staff.filter(person => matches(person.name + ' ' + person.email)).map(person => <tr key={person.id}><td>{person.name}</td><td>{person.email}</td><td><RoleSelect label={`Vai trò của ${person.name}`} value={person.role} onChange={role => commit({ ...club, staff: club.staff.map(item => item.id === person.id ? { ...item, role } : item) }, 'Đã cập nhật vai trò.')}/></td><td>{person.active ? 'Đang hoạt động' : 'Tạm ngừng'}</td><td><button onClick={() => commit({ ...club, staff: club.staff.map(item => item.id === person.id ? { ...item, active: !item.active } : item) }, 'Đã cập nhật trạng thái nhân sự.')}>{person.active ? 'Tạm ngừng' : 'Kích hoạt'}</button></td></tr>)}/></>
  else if (active === 'Kết quả đua') content = <><Table columns={['Giải đua', 'Ngựa', 'Ngày', 'Thứ hạng']} rows={club.races.map(item => <tr key={item.id}><td>{item.event}</td><td>{club.horses.find(horse => horse.id === item.horseId)?.name || '—'}</td><td>{item.date}</td><td>{item.position}</td></tr>)}/><h2>Ghi nhận kết quả đua</h2><form className="club-form" onSubmit={event => { event.preventDefault(); if (!race.event.trim() || !club.horses.some(horse => horse.id === race.horseId)) return setError('Vui lòng chọn ngựa và nhập tên giải đua.'); commit({ ...club, races: [...club.races, { ...race, event: race.event.trim(), position: Number(race.position), id: crypto.randomUUID() }] }, 'Đã ghi nhận kết quả đua.'); setRace({ ...race, event: '', date: '', position: 1 }) }}><label>Ngựa<select required value={race.horseId} onChange={event => setRace({ ...race, horseId: event.target.value })}>{club.horses.map(horse => <option key={horse.id} value={horse.id}>{horse.name}</option>)}</select></label><label>Giải đua<input required value={race.event} onChange={event => setRace({ ...race, event: event.target.value })}/></label><label>Ngày đua<input type="date" required value={race.date} onChange={event => setRace({ ...race, date: event.target.value })}/></label><label>Thứ hạng<input type="number" required min="1" max="100" value={race.position} onChange={event => setRace({ ...race, position: event.target.value })}/></label><button className="manager-primary-button" disabled={!club.horses.length}>Lưu kết quả</button></form></>
  else if (active === 'Báo cáo') content = <><div className="club-summary"><p>Tổng số ngựa: <b>{club.horses.length}</b></p><p>Ngựa đủ điều kiện: <b>{club.horses.filter(horse => horse.status === 'Đủ điều kiện').length}</b></p><p>Nhân sự hoạt động: <b>{club.staff.filter(person => person.active).length}</b></p><p>Kết quả đua: <b>{club.races.length}</b></p></div><button className="manager-primary-button" onClick={() => exportClubReport(club)}>Tải báo cáo ngựa CSV</button><h2>Nhật ký hoạt động</h2><Table columns={['Thời gian', 'Hoạt động']} rows={club.activity.map(item => <tr key={item.id}><td>{new Date(item.at).toLocaleString('vi-VN')}</td><td>{item.message}</td></tr>)}/></>
  else if (active === 'Cài đặt') content = <form className="club-form" onSubmit={event => { event.preventDefault(); if (!settings.name.trim() || !settings.location.trim()) return setError('Tên và địa chỉ không được để trống.'); commit({ ...club, ...settings, name: settings.name.trim(), location: settings.location.trim() }, 'Đã lưu cài đặt trung tâm.') }}><label>Tên trung tâm<input required value={settings.name} onChange={event => setSettings({ ...settings, name: event.target.value })}/></label><label>Địa chỉ<input required value={settings.location} onChange={event => setSettings({ ...settings, location: event.target.value })}/></label><label>Email liên hệ<input type="email" required value={settings.email} onChange={event => setSettings({ ...settings, email: event.target.value })}/></label><button className="manager-primary-button">Lưu cài đặt</button></form>
  return <section className="manager-card club-panel"><p className="club-demo-label">Không gian Club Manager mô phỏng · Dữ liệu lưu trên trình duyệt này</p>{notice && <p role="status" className="club-notice">{notice}</p>}{error && <p role="alert" className="form-error">{error}</p>}{content}</section>
}
